/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/* USART6 Pin Details -> APB2 Bus with Max 90MHz (PCLK2)
 * Address	->	0x40011400 to 0x400117FF
 * Rx		->	PG9
 * Tx		->	PG14
 * CTS		->	PG15
 * RTS		->	PG8
 * CK		->	PG7
 *
 * Interrupts
 * 		Position	->	71
 * 		Priority	->	78
 * 		Address		-> 0x0000015C
 * */


#include <stdint.h>

#include "stm32NucleoF429xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	for(;;);
}
